-- Colorscheme generated by https://github.com/arcticlimer/djanho
local M = {}

function M.setup()
	vim.cmd([[highlight clear]])

	if vim.fn.exists("syntax_on") then -- NOTE: optional
		vim.cmd("syntax reset")
	end

	vim.o.background = "dark"
	vim.g.colors_name = "cursordark"

	local highlight = function(group, bg, fg, attr)
		fg = fg and "guifg=" .. fg or ""
		bg = bg and "guibg=" .. bg or ""
		attr = attr and "gui=" .. attr or ""

		vim.api.nvim_command("highlight " .. group .. " " .. fg .. " " .. bg .. " " .. attr)
	end

	local link = function(target, group)
		vim.api.nvim_command("highlight! link " .. target .. " " .. group)
	end

	local Color3 = "#82D2CE"
	local Color4 = "#E394DC"
	local Color5 = "#EBC88D"
	local Color9 = "#d8dee9"
	local Color11 = "#303030"
	local Color10 = "#383838"
	local Color13 = "#ffffff"
	local Color0 = "#D6D6DD"
	local Color12 = "#505050"
	local Color2 = "#EFB080"
	local Color7 = "#141414"
	local Color6 = "#747474"
	local Color1 = "#83D6C5"
	local Color8 = "#1a1a1a"

	highlight("Operator", nil, Color0, nil)
	highlight("Keyword", nil, Color1, nil)
	highlight("Identifier", nil, Color0, nil)
	highlight("Function", nil, Color2, nil)
	highlight("Type", nil, Color2, nil)
	highlight("Type", nil, Color3, nil)
	highlight("String", nil, Color4, nil)
	highlight("Number", nil, Color5, nil)
	highlight("StatusLine", Color6, Color7, nil)
	highlight("WildMenu", Color8, Color9, nil)
	highlight("Pmenu", Color8, Color9, nil)
	highlight("PmenuSel", Color9, Color8, nil)
	highlight("PmenuThumb", Color8, Color9, nil)
	highlight("DiffAdd", Color10, nil, nil)
	highlight("DiffDelete", Color10, nil, nil)
	highlight("Normal", Color8, Color9, nil)
	highlight("Visual", Color11, nil, nil)
	highlight("CursorLine", Color11, nil, nil)
	highlight("ColorColumn", Color11, nil, nil)
	highlight("SignColumn", Color8, nil, nil)
	highlight("LineNr", nil, Color12, nil)
	highlight("TabLine", Color7, Color12, nil)
	highlight("TabLineSel", Color13, Color8, nil)
	highlight("TabLineFill", Color7, Color12, nil)
	highlight("TSPunctDelimiter", nil, Color9, nil)

	link("TSParameterReference", "TSParameter")
	link("Whitespace", "Comment")
	link("Operator", "Keyword")
	link("TSFuncMacro", "Macro")
	link("TSTag", "MyTag")
	link("TSLabel", "Type")
	link("TSPunctBracket", "MyTag")
	link("TSOperator", "Operator")
	link("TSRepeat", "Repeat")
	link("TSConstBuiltin", "TSVariableBuiltin")
	link("TSFloat", "Number")
	link("Macro", "Function")
	link("TSNumber", "Number")
	link("TSConditional", "Conditional")
	link("TSNamespace", "TSType")
	link("TSType", "Type")
	link("CursorLineNr", "Identifier")
	link("TSTagDelimiter", "Type")
	link("TSComment", "Comment")
	link("Conditional", "Operator")
	link("TSString", "String")
	link("TSParameter", "Constant")
	link("Repeat", "Conditional")
	link("TSFunction", "Function")
	link("TelescopeNormal", "Normal")
	link("Folded", "Comment")
	link("TSKeyword", "Keyword")
	link("TSProperty", "TSField")
	link("TSPunctSpecial", "TSPunctDelimiter")
	link("TSField", "Constant")
	link("NonText", "Comment")
	link("TSConstant", "Constant")
end

return M
